WebCLI/urls.py
# pages/urls.py
from django.urls import path
from .views.new_algorithm import new_algorithm
from .views.new_molecule import new_molecule
from .views.new_algorithm_type import new_algorithm_type
from .views.view_molecule import view_molecule
from .views.new_version import add_version, load_methods
from .views.update_algorithm import update_algorithm
from .views.compare_algorithms import AlgorithmComparisonView
from .views.algorithm_details_view import AlgorithmDetailsView, in_analysis, refresh_metrics
from .views.test_algorithm import test_algorithm
from .views.homepage import AlgorithmListView
from .views.my_algorithms import MyAlgorithmListView
from .forms import SignUpView
from .views.worker_api import handle_result

urlpatterns = [
    path('', AlgorithmListView.as_view(), name='home'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('newAlgorithm/', new_algorithm, name='newAlgorithm'),
    path('newMolecule/', new_molecule, name='newMolecule'),
    path('newAlgorithmType/', new_algorithm_type, name='newAlgorithmType'),
    path('algorithm/<int:algorithm_id>', AlgorithmDetailsView.as_view(), name='algorithm_details'),
    path('myAlgorithms/', MyAlgorithmListView.as_view(), name="myAlgorithms"),
    path('compare/<int:a1_id>/<int:a2_id>',
         AlgorithmComparisonView.as_view(), name="compare_algorithms"),
    path('addVersion/', add_version, name='add_version'),
    path('updateAlgorithm/', update_algorithm, name='updateAlgorithm'),
    path('handleResult', handle_result),
    path('test/', test_algorithm, name='test_algorithm'),
    path('methods_of_module/', load_methods, name='load_methods'),
    path('molecule/<int:molecule_id>', view_molecule, name='viewMolecule'),
    path('in_analysis/', in_analysis, name='in_analysis'),
    path('metrics/', refresh_metrics, name='refresh_metrics'),
]

WebMark/urls.py
from WebMark.settings import ROOT_DIR
from django.contrib import admin
from django.urls import path, include  # new

urlpatterns = [
    path(ROOT_DIR + 'admin/', admin.site.urls),
    path(ROOT_DIR + 'accounts/', include('django.contrib.auth.urls')),
    path(ROOT_DIR + '', include('WebCLI.urls')),  # new
]

WebCLI/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Algorithm_type(models.Model):
    type_name = models.TextField()

    def __str__(self):
        return self.type_name


class Molecule(models.Model):
    name = models.TextField()
    structure = models.TextField()
    active_orbitals = models.TextField(blank=True, default="")
    basis_set = models.TextField(default="")
    transformation = models.TextField(blank=True, default="")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('viewMolecule', args=[str(self.pk)])

    def __str__(self):
        return self.name


class Algorithm(models.Model):
    name = models.TextField()
    public = models.BooleanField()
    algorithm_type = models.ForeignKey(Algorithm_type, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article_link = models.URLField(blank=True)
    github_link = models.URLField(blank=True)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('algorithm_details', args=[str(self.pk)])

    def __str__(self):
        return self.name


class Algorithm_version(models.Model):
    algorithm_id = models.ForeignKey(Algorithm, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    algorithm = models.TextField()
    circuit = models.TextField(default="")
    optimizer_module = models.TextField(blank=True)
    optimizer_method = models.TextField(blank=True)

    def __str__(self):
        return str(self.timestamp)


class Metrics(models.Model):
    algorithm_version = models.ForeignKey(Algorithm_version, on_delete=models.CASCADE)
    molecule = models.ForeignKey(Molecule, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    measurements = models.IntegerField(null=True, blank=True)
    last_analyze_ok = models.BooleanField(default=False)
    in_analyze_queue = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=timezone.now)
    qubit_count = models.IntegerField(null=True, blank=True)
    gate_depth = models.IntegerField(null=True, blank=True)
    average_iterations = models.FloatField(null=True, blank=True)
    success_rate = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.molecule.name


class Average_history(models.Model):
    metrics = models.ForeignKey(Metrics, on_delete=models.CASCADE)
    data = models.FloatField(null=True, blank=True)
    iteration_number = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.iteration_number}:{self.data}'


class Accuracy_history(models.Model):
    metrics = models.ForeignKey(Metrics, on_delete=models.CASCADE)
    data = models.FloatField(null=True, blank=True)
    iteration_number = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.iteration_number}:{self.data}'

WebCLI/views.py
from WebMark.settings import ALGORITHMS_PER_PAGE, ROOT_DIR
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views import generic
from django.forms import ModelForm, Textarea, HiddenInput, Form
from django.forms import CharField
from django.forms.widgets import NumberInput
from django_tables2.columns.base import Column
from django_tables2.columns import TemplateColumn
from .models import Algorithm, Molecule, Algorithm_type, Algorithm_version, Metrics
from django.utils import timezone
from django.utils.decorators import method_decorator
from django_filters import AllValuesFilter, FilterSet
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin, Table
from django.http import HttpResponseBadRequest


class AlgorithmFilter(FilterSet):
    algorithm_type = AllValuesFilter(
        field_name='algorithm_type__type_name',
        empty_label="All algorithm types"
    )

    class Meta:
        model = Algorithm
        fields = ['algorithm_type']


class AlgorithmTable(Table):
    name = Column(linkify=True)
    github_link = Column(verbose_name='Github')
    article_link = Column(verbose_name='Article')
    pk = TemplateColumn(verbose_name='Compare',
                        template_name="WebCLI/compare.html", orderable=False)

    class Meta:
        model = Algorithm
        exclude = ('id', 'public')
        attrs = {'class': 'table table-hover table-sm'}

    def render_github_link(self, value):
        return format_html(f'<a href={value}>Github</a>')

    def render_article_link(self, value):
        return format_html(f'<a href={value}>Article</a>')


class AlgorithmListView(SingleTableMixin, FilterView):
    model = Algorithm
    template_name = "WebCLI/index.html"
    paginate_by = ALGORITHMS_PER_PAGE
    context_object_name = 'algorithms'
    queryset = Algorithm.objects.filter(public=True).order_by("name")
    filterset_class = AlgorithmFilter
    table_class = AlgorithmTable

    def get_context_data(self, **kwargs):
        context = super(AlgorithmListView, self).get_context_data(**kwargs)
        context['root_dir'] = ROOT_DIR
        return context


class MyAlgorithmListView(AlgorithmListView):

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return super(MyAlgorithmListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return Algorithm.objects.filter(user=self.request.user).order_by("name")


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class AlgorithmForm(ModelForm):
    class Meta:
        model = Algorithm
        fields = ['user', 'name', 'algorithm_type', 'public',
                  'article_link', 'github_link']
        widgets = {
            'name': Textarea(attrs={'rows': 1, 'cols': 50}),
            'user': HiddenInput(),
        }


class AlgorithmVersionForm(Form):
    algorithm = CharField(widget=Textarea)


class MetricsForm(ModelForm):
    class Meta:
        model = Metrics
        fields = ['algorithm_version', 'molecule', 'iterations',
                  'measurements', 'circuit_depth', 'accuracy']
        widgets = {
            'algorithm_version': HiddenInput(),
            'iterations': NumberInput(attrs={'min': 0, 'max': 1000000}),
            'measurements': NumberInput(attrs={'min': 0, 'max': 1000000}),
            'circuit_depth': NumberInput(attrs={'min': 0, 'max': 1000000}),
            'accuracy': NumberInput(attrs={'min': 0, 'max': 1000000}),
        }


@login_required
def new_algorithm(request):
    aform = AlgorithmForm(initial={'user': request.user})
    vform = AlgorithmVersionForm()
    if request.method == "POST":
        algorithm_form = AlgorithmForm(request.POST)
        new_algorithm = algorithm_form.save(commit=False)
        new_algorithm.user = request.user
        new_algorithm.save()
        algorithm = AlgorithmVersionForm(request.POST).data['algorithm']
        v = Algorithm_version(timestamp=timezone.now(), algorithm_id=new_algorithm,
                              algorithm=algorithm)
        v.save()
    data = {'algorithms': Algorithm.objects.filter(user=request.user), 'aform': aform,
            'vform': vform}
    return render(request, 'WebCLI/newAlgorithm.html', data)


def algorithm_details_view(request, algorithm_id):
    algorithm = Algorithm.objects.get(pk=algorithm_id)
    if not algorithm.public and request.user.pk != algorithm.user.pk:
        raise PermissionDenied
    molecule = ""
    versions = Algorithm_version.objects.filter(algorithm_id=algorithm).order_by('-timestamp')
    selectedVersion = versions[0]
    metrics = Metrics.objects.filter(algorithm_version=selectedVersion)
    selectedMetrics = None
    if len(metrics) > 0:
        molecule = metrics[0].molecule
        selectedMetrics = metrics[0]
    if request.method == "POST":
        if 'version_id' in request.POST:
            selectedVersion = Algorithm_version.objects.get(pk=request.POST.get('version_id'))
            metrics = Metrics.objects.filter(algorithm_version=selectedVersion)
            selectedMetrics = None
            if len(metrics) > 0:
                selectedMetrics = metrics[0]
        else:
            selectedMetrics = Metrics.objects.get(pk=request.POST.get('metrics_id'))
            selectedVersion = selectedMetrics.algorithm_version
            metrics = Metrics.objects.filter(algorithm_version=selectedVersion)
    data = {'algorithm': algorithm, 'versions': versions, 'selectedVersion': selectedVersion,
            'metrics': metrics, None), 'selectedMetrics': selectedMetrics, 'molecule': molecule}
    return render(request, 'WebCLI/algorithm.html', data)


class MoleculeForm(ModelForm):
    class Meta:
        model = Molecule
        fields = ['name', 'structure']
        widgets = {
            'name': Textarea(attrs={'rows': 1, 'cols': 50}),
        }


@login_required
def new_molecule(request):
    form = MoleculeForm()
    if request.method == "POST":
        m = MoleculeForm(request.POST)
        m.save()
    data = {'molecules': Molecule.objects.all(), 'form': form}
    return render(request, 'WebCLI/newMolecule.html', data)


class AlgorithmTypeForm(ModelForm):
    class Meta:
        model = Algorithm_type
        fields = ['type_name']
        widgets = {
            'type_name': Textarea(attrs={'rows': 1, 'cols': 50}),
        }


@login_required
def new_algorithm_type(request):
    form = AlgorithmTypeForm()
    if request.method == "POST":
        m = AlgorithmTypeForm(request.POST)
        m.save()
    data = {'types': Algorithm_type.objects.all(), 'form': form}
    return render(request, 'WebCLI/newAlgorithmType.html', data)


@login_required
def add_metrics(request):
    av = Algorithm_version.objects.get(pk=request.GET.get("index"))
    if request.user.pk != av.algorithm_id.user.pk:
        raise PermissionDenied

    if request.method == "POST":
        form = MetricsForm(request.POST).data
        for f in ['iterations', 'measurements', 'circuit_depth', 'accuracy']:
            if form[f]:
                data = form[f]
                try:
                    number = float(data)
                    if number < 0:
                        return HttpResponseBadRequest('Input value must be positive')
                except ValueError:
                    return HttpResponseBadRequest('Metrics input needs to be numeric')
        m = Molecule.objects.get(pk=int(form['molecule']))
        existing = Metrics.objects.filter(algorithm_version=av, molecule=m)
        if len(existing) > 0:
            metrics = MetricsForm(request.POST, instance=existing[0])
            metrics.save()
        else:
            metrics = MetricsForm(request.POST)
            metrics.save()
        return redirect(av.algorithm_id)
    form = MetricsForm(initial={'algorithm_version': av, 'verified': False})
    data = {'algorithm': av.algorithm_id, 'version': av, 'form': form}
    return render(request, 'WebCLI/addMetrics.html', data)


def add_version(request):
    a = Algorithm.objects.get(pk=request.GET.get("index"))
    if request.user.pk != a.user.pk:
        raise PermissionDenied

    if request.method == "POST":
        algorithm = AlgorithmVersionForm(request.POST).data['algorithm']
        version = Algorithm_version(algorithm_id=a, timestamp=timezone.now(), algorithm=algorithm)
        version.save()
        return redirect(a)
    last_version = Algorithm_version.objects.filter(algorithm_id=a).order_by('-timestamp')[0]
    form = AlgorithmVersionForm(initial={'algorithm': last_version.algorithm})
    data = {'algorithm': a, 'form': form}
    return render(request, 'WebCLI/addVersion.html', data)


def update_algorithm(request):
    a = Algorithm.objects.get(pk=request.GET.get("index"))
    if request.user.pk != a.user.pk:
        raise PermissionDenied

    if request.method == "POST":
        form = AlgorithmForm(request.POST, instance=a)
        form.save()
        return redirect(a)
    return render(request, 'WebCLI/updateDetails.html', {'form': AlgorithmForm(instance=a)})


def compare_algorithms(request, a1_id, a2_id):
    if not a1_id.isnumeric() or not a2_id.isnumeric():  # ignore garbage values
        return redirect("home")

    queryset = Algorithm.objects.filter(pk=a1_id) | Algorithm.objects.filter(pk=a2_id)
    if len(queryset) != 2:  # check that we have found two unique algorithms
        return redirect("home")

    (versions1, versions2) = (
        Algorithm_version.objects.filter(algorithm_id=queryset[0]).order_by('-timestamp'),
        Algorithm_version.objects.filter(algorithm_id=queryset[1]).order_by('-timestamp')
    )

WebCLI/views/homepage.py
from WebMark.settings import ALGORITHMS_PER_PAGE, ROOT_DIR
from django.utils.html import format_html
from django_tables2.columns.base import Column
from django_tables2.columns import TemplateColumn
from django_filters import AllValuesFilter, FilterSet
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin, Table
from ..models import Algorithm


class AlgorithmFilter(FilterSet):
    algorithm_type = AllValuesFilter(
        field_name='algorithm_type__type_name',
        empty_label="All algorithm types"
    )

    class Meta:
        model = Algorithm
        fields = ['algorithm_type']


class AlgorithmTable(Table):
    name = Column(linkify=True)
    github_link = Column(verbose_name='Github')
    article_link = Column(verbose_name='Article')
    pk = TemplateColumn(verbose_name='Compare',
                        template_name="WebCLI/compare.html", orderable=False)

    class Meta:
        model = Algorithm
        exclude = ('id', 'public')
        attrs = {'class': 'table table-hover table-sm'}

    def render_github_link(self, value):
        return format_html(f'<a href={value}>Github</a>')

    def render_article_link(self, value):
        return format_html(f'<a href={value}>Article</a>')


class AlgorithmListView(SingleTableMixin, FilterView):
    model = Algorithm
    template_name = "WebCLI/index.html"
    paginate_by = ALGORITHMS_PER_PAGE
    context_object_name = 'algorithms'
    queryset = Algorithm.objects.filter(public=True).order_by("name")
    filterset_class = AlgorithmFilter
    table_class = AlgorithmTable

    def get_context_data(self, **kwargs):
        context = super(AlgorithmListView, self).get_context_data(**kwargs)
        context['root_dir'] = ROOT_DIR
        return context

WebCLI/views/my_algorithms.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from ..models import Algorithm
from .homepage import AlgorithmListView


class MyAlgorithmListView(AlgorithmListView):

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return super(MyAlgorithmListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return Algorithm.objects.filter(user=self.request.user).order_by("name")

WebCLI/views/view_molecule.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from ..models import Molecule


@login_required
def view_molecule(request, molecule_id):
    m = Molecule.objects.get(pk=molecule_id)
    data = {'molecule': m}
    return render(request, 'WebCLI/molecule.html', data)

templates/WebCLI/addMetrics.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}Add metrics manually{% endblock %}

{% block content %}
    <div class="p-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Add metrics to algorithm</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>name</th>
                    <td>{{ algorithm.name }}</td>
                </tr>
                <tr>
                    <th>type</th>
                    <td>{{ algorithm.algorithm_type.type_name }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th colspan="2">Algorithm
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <code>{{ version.algorithm|linebreaks }}</code>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
        {% endbuttons %}
    </form>

{% endblock %}

templates/WebCLI/addVersion.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}Update algorithm{% endblock %}

{% block content %}
    <div class="p-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Update algorithm</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>name</th>
                    <td>{{ algorithm.name }}</td>
                </tr>
                <tr>
                    <th>type</th>
                    <td>{{ algorithm.algorithm_type.type_name }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <form method="post" method-url="{% url 'load_methods' %}" id="versionForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
        {% endbuttons %}
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_optimizer_module").change(function () {
            var url = $("#versionForm").attr("method-url")
            var module = $(this).val();

            $.ajax({ 
                url: url, 
                data: {
                    'module': module 
                },
                success: function (data) { 
                    $("#id_optimizer_method").html(data);
                }
            });

        });
    </script>
{% endblock %}

templates/WebCLI/circuit.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}Circuit input testing{% endblock %}

{% block content %}
<h2>{{ circuit_input }}</h2>
<div class="form-group basic-textarea rounded-corners">
    <textarea disabled value="" class="form-control rounded-0" id="id_textarea"></textarea>
</div>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <div class="text-center">
        <button class="btn btn-success" type="submit" onClick=getCircuit();>Submit</button>
        <button class="btn btn-primary" type="button" onClick=add();>Add</button>
        <button class="btn btn-secondary" type="reset" onClick=reset();>Reset</button>
    </div>
    {% endbuttons %}
    <script>
        var gate = "";
        var param = "";
        var oldParam;
        var value = "";

        function changeContent(str1, which) {
            var x = document.getElementById('id_circuit');
            if (which == "g") {
                gate = str1 + "(";
            } if (which == "p1") {
                param = str1 + "=";
            } if (which == "p2") {
                oldParam = param + value;
                param = oldParam + ", " + str1 + "=";
            } if (which == "val1") {
                value = str1;
            } if (which == "val2") {
                value = "[" + value + "," + str1 + "]";
            } if (which == "pstr") {
                x.value = x.value.replace(')', '') + ", paulistring=" + '"' + str1 + '"' + ")";
            } else {
                x.value = gate + param + value + ")";
            }
        }


        function getCircuit() {
            var x = document.getElementById('id_circuit');
            if (x.value == "") {
                return;
            }
            var y = document.getElementById('id_textarea');
            x.value = y.value + " + " + x.value;
        }


        function add() {
            var x = document.getElementById('id_circuit');
            var y = document.getElementById('id_textarea');
            if (y.value == "") {
                y.value = x.value
            } else {
                y.value = y.value + " + " + x.value;
            }
            x.value = "";
            gate = "";
            param = "";
            oldParam = "";
            value = "";
        }

        function reset() {
            var x = document.getElementById('id_circuit');
            x.value = "";
            gate = "";
            param = "";
            oldParam = "";
            value = "";
        }
    </script>
    <div>
        <select onchange=changeContent(this.value,"g");>
            <option value="" selected disabled>Choose a gate</option>
            {% for g in gates %}
            <option value="{{g}}">{{ g }}</option>
            {% endfor %}
        </select>
        <select onchange=changeContent(this.value,"p1");>
            <option value="" selected disabled>1st parameter</option>
            {% for p in params %}
            <option value="{{p}}">{{ p }}</option>
            {% endfor %}
        </select>
        <select onchange=changeContent(this.value,"p2");>
            <option value="" selected>add parameter</option>
            {% for p in params %}
            <option value="{{p}}">{{ p }}</option>
            {% endfor %}
        </select>

        <input type="number" placeholder="single int" min=0 max=1000 step="0.1" value=""
            onchange=changeContent(this.value,"val1");>
        <input type="number" placeholder="2nd int" min=0 max=1000 step="0.1" value=""
            onchange=changeContent(this.value,"val2");>
    </div>
    <div>
        <input type="text" placeholder="Paulistring" onchange=changeContent(this.value,"pstr");>
    </div>
</form>
{% endblock %}

templates/WebCLI/compare.html
<label for="checkbox{{ value }}" class="sr-only">Compare?</label>
<input id="checkbox{{ value }}" name="checkbox" algorithm="{{ value }}" type="checkbox">

templates/WebCLI/in_analysis.html
{% for m in molecules %}
    <br>
    Analysis in progress: {{ m }}
{% endfor %}

templates/WebCLI/index.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block title %}Main page{% endblock %}

{% block content %}

    {% if filter %}
        <form action="" method="get" name="filterForm" class="form form-inline"
              onchange="document.getElementsByName('filterForm')[0].submit();">
            {% bootstrap_form filter.form layout='inline' %}
        </form>
    {% endif %}

    {% render_table table 'django_tables2/bootstrap4.html' %}
    <div class="d-flex flex-row">
        <a id="compare" href="" class="btn btn-primary mr-2">Compare</a>
        <button class="btn btn-danger" id="clearSelections" onclick="clearStorageAndReload()">
            Clear selections
        </button>
    </div>
    <script>
        const checkboxes = document.getElementsByName("checkbox");
        const checkedJSON = window.sessionStorage.getItem("checked") || "[]";
        const checked = JSON.parse(checkedJSON);
        let checkboxesDisabled = false;

        updateButtonStates();
        initializeCheckboxes();
        updateCheckboxStates();

        function initializeCheckboxes() {
            for (const checkbox of checkboxes) {
                // making sure that checkboxes are not checked after reload on all browsers
                checkbox.checked = false;

                // check checkboxes again after a reload
                if (checked.includes(checkbox.getAttribute("algorithm"))) {
                    checkbox.checked = true;
                }

                checkbox.onclick = function () {
                    const algorithm_id = this.getAttribute('algorithm');
                    if (checked.includes(algorithm_id)) {
                        checked.splice(checked.indexOf(algorithm_id), 1);
                    } else if (checked.length < 2) {
                        checked.push(algorithm_id);
                    }
                    window.sessionStorage.setItem("checked", JSON.stringify(checked));
                    updateButtonStates();
                    updateCheckboxStates();
                }, { passive: true };
            }
        }

        function updateCheckboxStates() {
            if (checkboxesDisabled && checked.length !== 2) {
                checkboxesDisabled = false;
                enableCheckboxes();
            }
            if (!checkboxesDisabled && checked.length === 2) {
                checkboxesDisabled = true;
                disableCheckboxes();
            }
        }

        // disables all checkboxes except the ones that are currently selected
        function disableCheckboxes() {
            checkboxesDisabled = true;
            for (const checkbox of checkboxes) {
                checkbox.disabled = !checkbox.checked;
            };
        }

        function enableCheckboxes() {
            for (const checkbox of checkboxes) {
                checkbox.disabled = false;
            }
        }

        // enables and disables compare and clear selections
        // buttons based on how many algorithms are currently selected
        function updateButtonStates() {
            const compareButton = document.getElementById("compare");
            const clearButton = document.getElementById("clearSelections");

            if (checked.length !== 2) {
                compareButton.href = ""; // disables the link
                compareButton.classList.add('disabled');
            } else {
                compareButton.href = "/{{ root_dir }}" + "compare/" + checked[0] + "/" + checked[1];
                compareButton.classList.remove("disabled");
            }
            clearButton.disabled = checked.length === 0;
        }

        // clears storage and reloads the page to initialize everything again
        function clearStorageAndReload() {
            window.sessionStorage.removeItem("checked");
            window.location.reload();
        }
    </script>
{% endblock %}

templates/WebCLI/methods_of_module.html
{% for method in methods %}
    <option value="{{ method }}">{{ method }}</option>
{% endfor %}

templates/WebCLI/metrics.html
<metrics>
    <in_analyze_queue>{{ metrics.in_analyze_queue }}</in_analyze_queue>
</metrics>

templates/WebCLI/molecule.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}View molecule{% endblock %}

{% block content %}
    <div class="d-flex flex-row flex-wrap justify-content-center">
        <div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Molecule details</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Name</th>
                        <td>{{ molecule.name }}</td>
                    </tr>
                    <tr>
                        <th>Geometry</th>
                        <td>{{ molecule.structure }}</td>
                    </tr>
                    <tr>
                        <th>Active orbitals</th>
                        <td>{{ molecule.active_orbitals }}</td>
                    </tr>
                    <tr>
                        <th>Basis set</th>
                        <td>{{ molecule.basis_set }}</td>
                    </tr>
                    <tr>
                        <th>Transformation</th>
                        <td>{{ molecule.transformation }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/WebCLI/newAlgorithm.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}Add a new algorithm{% endblock %}

{% block content %}
    <h2>Existing algorithms</h2>
    {% for a in algorithms %}
        <div class="text-center"><a href="{{ a.get_absolute_url }}">{{a.name}}</a></div>
    {% endfor %}
    <h2>New algorithm</h2>
    <form method="post" method-url="{% url 'load_methods' %}" id="versionForm">
        {% csrf_token %}
        {% bootstrap_form aform %}
        {% bootstrap_form vform %}
        {% buttons %}
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
        {% endbuttons %}
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_optimizer_module").change(function () {
            var url = $("#versionForm").attr("method-url")
            var module = $(this).val();

            $.ajax({ 
                url: url, 
                data: {
                    'module': module 
                },
                success: function (data) { 
                    $("#id_optimizer_method").html(data);
                }
            });

        });
    </script>
{% endblock %}